In [23]:
import pandas as pd
import re
import sys

In [17]:
# sys.path.append("..")
# sys.path.append(".")

In [18]:
print(sys.path)

['/Users/janas/Documents/Python_Projects/DisasterTweets/notebooks', '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', '', '/Users/janas/.local/share/virtualenvs/DisasterTweets-4PiDNLHM/lib/python3.9/site-packages', '/Users/janas/.local/share/virtualenvs/DisasterTweets-4PiDNLHM/lib/python3.9/site-packages/IPython/extensions', '/Users/janas/.ipython', '..', '.', '/Users/janas/Documents/Python_Projects/DisasterTweets/data']

In [19]:
path = "/Users/janas/Documents/Python_Projects/DisasterTweets/data/"
df = pd.read_csv(path+"train.csv")

In [34]:
df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [42]:
df[~df['location'].isnull()].head(20)

,id,keyword,location,text,target,hashtags
31,48,ablaze,Birmingham,@bbcmtd Wholesale Markets ablaze http://t.co/l...,1,[]
32,49,ablaze,Est. September 2012 - Bristol,We always try to bring the heavy. #metal #RT h...,0,"[#metal, #RT]"
33,50,ablaze,AFRICA,#AFRICANBAZE: Breaking news:Nigeria flag set a...,1,[#AFRICANBAZE]
34,52,ablaze,"Philadelphia, PA",Crying out for more! Set me ablaze,0,[]
35,53,ablaze,"London, UK",On plus side LOOK AT THE SKY LAST NIGHT IT WAS...,0,[]
36,54,ablaze,Pretoria,@PhDSquares #mufc they've built so much hype a...,0,[#mufc]
37,55,ablaze,World Wide!!,INEC Office in Abia Set Ablaze - http://t.co/3...,1,[]
39,57,ablaze,Paranaque City,Ablaze for you Lord :D,0,[]
40,59,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...,0,[#nsfw]
42,62,ablaze,milky way,Had an awesome time visiting the CFC head offi...,0,[]
46,66,ablaze,"GREENSBORO,NORTH CAROLINA",How the West was burned: Thousands of wildfire...,1,[]
48,68,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...,0,[#nsfw]
49,71,ablaze,England.,First night with retainers in. It's quite weir...,0,[]
50,73,ablaze,"Sheffield Township, Ohio",Deputies: Man shot before Brighton home set ab...,1,[]
51,74,ablaze,India,Man wife get six years jail for setting ablaze...,1,[]
52,76,ablaze,Barbados,SANTA CRUZ ÛÓ Head of the St Elizabeth Police...,0,[]
53,77,ablaze,Anaheim,Police: Arsonist Deliberately Set Black Church...,1,[]
54,78,ablaze,Abuja,Noches El-Bestia '@Alexis_Sanchez: happy to se...,0,[]
55,79,ablaze,USA,#Kurds trampling on Turkmen flag later set it ...,1,"[#Kurds, #Diyala]"
56,80,ablaze,South Africa,TRUCK ABLAZE : R21. VOORTREKKER AVE. OUTSIDE O...,1,[]

In [26]:
regex = re.compile("\#\w+")

In [28]:
regex.findall("Our Deeds are the #Reason of this #earthquake May ALLAH Forgive us all")

['#Reason', '#earthquake']

In [30]:
def find_hashtags(text):
    regex = re.compile("\#\w+")
    return regex.findall(text)

In [31]:
df['hashtags'] = df['text'].apply(find_hashtags)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
 5   hashtags  7613 non-null   object
dtypes: int64(2), object(4)
memory usage: 357.0+ KB

In [22]:
for idx, row in df.head().iterrows():
    print(row['text'])

Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all
Forest fire near La Ronge Sask. Canada
All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected
13,000 people receive #wildfires evacuation orders in California
Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school

In [33]:
df.head()

,id,keyword,location,text,target,hashtags
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1,[#earthquake]
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1,[]
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1,[]
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1,[#wildfires]
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1,"[#Alaska, #wildfires]"